export * from "./01/trebuchet";
export * from "./02/cubeConundrum";
export * from "./03/gearRatios";
export * from "./04/scratchcards";
export * from "./05/ifYouGiveASeedAFertilizer";
export * from "./06/waitForIt";
export * from "./07/camelCards";
export * from "./08/hauntedWasteland";
export * from "./09/mirageMaintenance";
