name: Static checks

on: push

jobs:
  staticChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn type:check
      - run: yarn lint:check
      - run: yarn prettier:check
